### ISSUE TITLE
Cannot reproduce the results

### ISSUE THREAD

**Issue by MarkDeng1** [ubc-vision/Prompting-Hard-Hardly-Prompting#11]
When i run `python main_textual_inversion.py --base configs/latent-diffusion/inversion_config.yaml --train True`
Using your provided yaml file, and test it using own data. The result is poor. 

Some of inferred prompt:
```
{"inferred_prompt": "Aphoto</w>of</w>busof</w>color</w>"}
{"inferred_prompt": "Aphoto</w>of</w>busof</w>color</w>"}
```
It seems the optimization process did not work at all. 

I use the following yaml file:
```
model:
  base_learning_rate: 0.8
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 800
    timesteps: 500 #1000
    first_stage_key: "image"
    cond_stage_key: "caption"
    negative_image_key: "negativeimage"
    image_size: 64
    channels: 4
    cond_stage_trainable: True   # Note: different from the one we trained before
    conditioning_key: crossattn
    #monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    #model_lr: 10.0

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 1 ] #10000
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512 #256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 16
    train:
      target: ldm.data.imageloader.CustomTrain
      params:
        image_path: "/path/to/own/image/53bbe731-28c3-4d63-a152-984df09b87d7.jpg"

lightning:
  trainer:
    benchmark: True
    max_steps: 400
    accumulate_grad_batches: 3

```
